name: Deploy slider server when notebooks change
on:
    push:
        branches:
            - master
        paths-ignore:
            - "website/**"
    workflow_dispatch:

jobs:
    deploy-slider-server:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v2

            - name: Push to deploy
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: deploy
                  FOLDER: .
